# Settings file for libra program
# See http://pyserial.wiki.sourceforge.net/pySerial

[serial]
device=Default
regex=(\d)\.(\d)
port=COM1
baudrate=2400
bytesize=EIGHTBITS
parity=PARITY_NONE
stopbits=STOPBITS_ONE
timeout=0.5
